/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlJFAgregarCliente;
import Control.ControlJFAgregarProducto;
import Control.ControlJFActualizarCliente;
import Control.ControlJFActualizarProducto;
import Control.ControlJFProductoSeparado;
import Control.ControlJFRegistroVenta;
import Modelo.IO;

/**
 *
 * @author Gerardo
 */
public class JFMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFMenu
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public JFMenu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        bArchivo = new javax.swing.JMenu();
        bCerrar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        bAgregarCliente = new javax.swing.JMenuItem();
        bActualizarCliente = new javax.swing.JMenuItem();
        bConsultarCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        bAgregarProducto = new javax.swing.JMenuItem();
        bModificarProducto = new javax.swing.JMenuItem();
        bConsultarProducto = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        bRegistroVenta = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        bProductoSeparado = new javax.swing.JMenuItem();
        bInventario = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Wallpaper Menu.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bArchivo.setText("Archivo");

        bCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Menu Cerrar.png"))); // NOI18N
        bCerrar.setText("Cerrar");
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });
        bArchivo.add(bCerrar);

        jMenuBar1.add(bArchivo);

        jMenu3.setText("Administrar");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Menu Clientes.png"))); // NOI18N
        jMenu1.setText("Clientes");

        bAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Menu Agregar Cliente.png"))); // NOI18N
        bAgregarCliente.setText("Agregar Cliente");
        bAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(bAgregarCliente);

        bActualizarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Menu Actualizar Cliente.png"))); // NOI18N
        bActualizarCliente.setText("Actualizar Cliente");
        bActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(bActualizarCliente);

        bConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Menu Consultar Cliente.png"))); // NOI18N
        bConsultarCliente.setText("Consultar Cliente");
        jMenu1.add(bConsultarCliente);

        jMenu3.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Menu Productos.png"))); // NOI18N
        jMenu2.setText("Productos");

        bAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Menu Agregar Producto.png"))); // NOI18N
        bAgregarProducto.setText("Agregra Nuevo Producto");
        bAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(bAgregarProducto);

        bModificarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Menu Actualizar Producto.png"))); // NOI18N
        bModificarProducto.setText("Actualizar Producto");
        bModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(bModificarProducto);

        bConsultarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Menu Consultar Producto.png"))); // NOI18N
        bConsultarProducto.setText("Consultar Producto");
        jMenu2.add(bConsultarProducto);

        jMenu3.add(jMenu2);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Menu Usuarios.png"))); // NOI18N
        jMenu6.setText("Usuarios");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Menu Consultar Usuarios.png"))); // NOI18N
        jMenuItem5.setText("Consultar Usuarios");
        jMenu6.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Menu Modificar Usuarios.png"))); // NOI18N
        jMenuItem6.setText("Modificar Usuarios");
        jMenu6.add(jMenuItem6);

        jMenu3.add(jMenu6);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ventas");

        bRegistroVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Menu Ventas.png"))); // NOI18N
        bRegistroVenta.setText("Registrar Ventas");
        bRegistroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistroVentaActionPerformed(evt);
            }
        });
        jMenu4.add(bRegistroVenta);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Consultar");

        bProductoSeparado.setText("Producto Separado");
        bProductoSeparado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProductoSeparadoActionPerformed(evt);
            }
        });
        jMenu5.add(bProductoSeparado);

        bInventario.setText("Inventario");
        bInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInventarioActionPerformed(evt);
            }
        });
        jMenu5.add(bInventario);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed

        IO.imprimir("Aplicación Finalizada");
        System.exit(0);
    }//GEN-LAST:event_bCerrarActionPerformed

    private void bAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarClienteActionPerformed
        ControlJFAgregarCliente ir = new ControlJFAgregarCliente();

    }//GEN-LAST:event_bAgregarClienteActionPerformed

    private void bAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarProductoActionPerformed
        ControlJFAgregarProducto ir = new ControlJFAgregarProducto();
    }//GEN-LAST:event_bAgregarProductoActionPerformed

    private void bModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarProductoActionPerformed
        ControlJFActualizarProducto ir = new ControlJFActualizarProducto();
    }//GEN-LAST:event_bModificarProductoActionPerformed

    private void bActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarClienteActionPerformed
        ControlJFActualizarCliente ir = new ControlJFActualizarCliente();
    }//GEN-LAST:event_bActualizarClienteActionPerformed

    private void bRegistroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistroVentaActionPerformed
        ControlJFRegistroVenta ir = new ControlJFRegistroVenta();
    }//GEN-LAST:event_bRegistroVentaActionPerformed

    private void bProductoSeparadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProductoSeparadoActionPerformed
       ControlJFProductoSeparado ir = new ControlJFProductoSeparado();
    }//GEN-LAST:event_bProductoSeparadoActionPerformed

    private void bInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInventarioActionPerformed
       //ControlJFInventario ir = new ControlJFInventario();
    }//GEN-LAST:event_bInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem bActualizarCliente;
    public javax.swing.JMenuItem bAgregarCliente;
    public javax.swing.JMenuItem bAgregarProducto;
    public javax.swing.JMenu bArchivo;
    public javax.swing.JMenuItem bCerrar;
    public javax.swing.JMenuItem bConsultarCliente;
    public javax.swing.JMenuItem bConsultarProducto;
    public javax.swing.JMenuItem bInventario;
    public javax.swing.JMenuItem bModificarProducto;
    public javax.swing.JMenuItem bProductoSeparado;
    public javax.swing.JMenuItem bRegistroVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
